venue: "Newcastle University"
address: "Henry Daysh Building, PGR Learning Lab R6.19"
country: "gb"
language: "en"
latitude: "54.980533"
longitude: "-1.614660"
humandate: "2025-04-22"
humantime: "09:00 - 17:00"
startdate: 2025-04-22
enddate: 2025-04-22
instructor: ["Dr Jannetta Steyn"]
helper: ["Carol Booth"]
email: ["carol.booth2@newcastle.ac.uk", "jannetta.steyn@newcastle.ac.uk"]
collaborative_notes: https://hackmd.io/@rseteam-ncl/2025-04-22-NCL
eventbrite:  
what3words: bars.hips.hired
